# Generated by Django 4.2.7 on 2026-03-12 00:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0093_remove_inventariodiario_reporte_and_more'),
        ('tiempos_barco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportediarioembarcacion',
            name='archivo_pdf_url',
        ),
        migrations.AddField(
            model_name='bitacoratiempo',
            name='estatus_operativo',
            field=models.CharField(default='Operando', max_length=50),
        ),
        migrations.AddField(
            model_name='reportediarioembarcacion',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tiempos_barco/reportes_diarios_flota/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='PosicionEmbarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('punto', django.contrib.gis.db.models.fields.PointField(help_text='Longitud y Latitud', srid=4326)),
                ('velocidad_nudos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.sitio')),
            ],
            options={
                'verbose_name': 'Posición de Embarcación',
                'verbose_name_plural': 'Posiciones de Embarcaciones',
                'db_table': 'posicion_embarcacion',
            },
        ),
    ]
