# Generated by Django 4.2.7 on 2025-10-02 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'embarcacion',
            },
        ),
        migrations.CreateModel(
            name='EstadoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'estado_cobro',
            },
        ),
        migrations.CreateModel(
            name='OTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_trabajo', models.CharField(max_length=100, unique=True)),
                ('descripcion_trabajo', models.TextField()),
                ('responsable_proyecto', models.CharField(max_length=200)),
                ('responsable_cliente', models.CharField(max_length=200)),
                ('oficio_ote', models.CharField(max_length=100)),
                ('estatus_ote', models.IntegerField(choices=[(1, 'Programada'), (2, 'En Proceso'), (3, 'Terminada'), (4, 'Cancelada')], default=1)),
                ('fecha_inicio_programada', models.DateField()),
                ('fecha_termino_programada', models.DateField()),
                ('estatus', models.IntegerField(default=1)),
                ('comentario', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ote',
            },
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('orden', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'paso',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('nivel_afectacion', models.CharField(choices=[('TRABAJO', 'TRABAJO'), ('PARTIDA', 'PARTIDA')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sitio',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'unidad_medida',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('nivel_afectacion', models.CharField(choices=[('PTE', 'PTE'), ('OTE', 'OTE'), ('PARTIDA', 'PARTIDA'), ('PRODUCCION', 'PRODUCCION')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo',
                'unique_together': {('nivel_afectacion', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='PTEHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficio_pte', models.CharField(max_length=100, unique=True)),
                ('oficio_solicitud', models.CharField(max_length=100)),
                ('descripcion_trabajo', models.TextField()),
                ('fecha_solicitud', models.DateField()),
                ('plazo_dias', models.IntegerField()),
                ('id_orden_trabajo', models.CharField(max_length=100)),
                ('responsable_proyecto', models.CharField(max_length=200)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'En Proceso'), (3, 'Terminado'), (4, 'Cancelado')], default=1)),
                ('id_tipo', models.ForeignKey(limit_choices_to={'tipo': 'PTE'}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.tipo')),
            ],
            options={
                'db_table': 'pte_header',
            },
        ),
        migrations.CreateModel(
            name='PTEDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_homologado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estatus_pte', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'En Proceso'), (3, 'Completado'), (4, 'Rechazado')], default=1)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('id_paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.paso')),
                ('id_pte_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operaciones.pteheader')),
            ],
            options={
                'db_table': 'pte_detalle',
                'ordering': ['id_paso__orden'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_partida', models.CharField(max_length=100)),
                ('descripcion_concepto', models.TextField()),
                ('anexo', models.CharField(blank=True, max_length=100)),
                ('partida_extraordinaria', models.CharField(blank=True, max_length=100)),
                ('precio_unitario_mn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_unitario_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_pte', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_pte2', models.DecimalField(decimal_places=2, max_digits=15)),
                ('costo_directo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estatus_pues', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Suspendido')], default=1)),
                ('anexo_liberado', models.CharField(blank=True, max_length=100)),
                ('estatus', models.BooleanField(default=True)),
                ('id_sitio', models.ForeignKey(limit_choices_to={'nivel_afectacion': 'PARTIDA'}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.sitio')),
                ('id_unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.unidadmedida')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_produccion', models.DateField()),
                ('volumen_produccion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('importe_mn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('importe_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('responsable_proyecto', models.CharField(max_length=200)),
                ('id_embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.embarcacion')),
                ('id_estado_cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.estadocobro')),
                ('id_ote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.ote')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.producto')),
                ('id_sitio_partida', models.ForeignKey(limit_choices_to={'nivel_afectacion': 'PARTIDA'}, on_delete=django.db.models.deletion.CASCADE, related_name='producciones_partida', to='operaciones.sitio')),
                ('id_sitio_trabajo', models.ForeignKey(limit_choices_to={'nivel_afectacion': 'TRABAJO'}, on_delete=django.db.models.deletion.CASCADE, related_name='producciones_trabajo', to='operaciones.sitio')),
                ('id_tipo_partida', models.ForeignKey(limit_choices_to={'tipo': 'PARTIDA'}, on_delete=django.db.models.deletion.CASCADE, related_name='producciones_partida', to='operaciones.tipo')),
                ('id_tipo_produccion', models.ForeignKey(limit_choices_to={'tipo': 'PRODUCCION'}, on_delete=django.db.models.deletion.CASCADE, related_name='producciones_tipo', to='operaciones.tipo')),
            ],
            options={
                'db_table': 'produccion',
            },
        ),
        migrations.AddField(
            model_name='ote',
            name='id_oficio_pte',
            field=models.ForeignKey(db_column='id_oficio_pte', on_delete=django.db.models.deletion.CASCADE, to='operaciones.pteheader', to_field='oficio_pte'),
        ),
        migrations.AddField(
            model_name='ote',
            name='id_tipo',
            field=models.ForeignKey(limit_choices_to={'tipo': 'OTE'}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.tipo'),
        ),
    ]
