# Generated by Django 4.2.7 on 2025-10-07 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('comentario', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'embarcacion',
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('nivel_afectacion', models.IntegerField(choices=[('1', 'PTE'), ('2', 'OT'), ('3', 'COBRO'), ('4', 'PASOS PTE')], default=0, max_length=1)),
                ('comentario', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cat_estatus',
            },
        ),
        migrations.CreateModel(
            name='OTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_trabajo', models.CharField(max_length=100, unique=True)),
                ('descripcion_trabajo', models.TextField()),
                ('responsable_cliente', models.CharField(max_length=200)),
                ('oficio_ote', models.CharField(max_length=100)),
                ('fecha_inicio_programada', models.DateField()),
                ('fecha_termino_programada', models.DateField()),
                ('estatus', models.IntegerField(default=1)),
                ('comentario', models.TextField(blank=True)),
                ('id_embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.embarcacion')),
                ('id_estatus_ote', models.ForeignKey(limit_choices_to={'nivel_afectacion': 2}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.estatus')),
            ],
            options={
                'db_table': 'ot',
            },
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('orden', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('importancia', models.FloatField(default=0)),
                ('comentario', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'paso',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ResponsableProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('comentario', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'responsable_proyecto',
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('nivel_afectacion', models.IntegerField(choices=[('1', 'PARTIDA'), ('2', 'TRABAJO')], default=0, max_length=1)),
                ('comentario', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sitio',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('nivel_afectacion', models.IntegerField(choices=[('1', 'PTE'), ('2', 'OT'), ('3', 'PARTIDA'), ('4', 'PRODUCCION')], default=0, max_length=1)),
                ('comentario', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('comentario', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'unidad_medida',
            },
        ),
        migrations.CreateModel(
            name='PTEHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficio_pte', models.CharField(max_length=100, unique=True)),
                ('oficio_solicitud', models.CharField(max_length=100)),
                ('descripcion_trabajo', models.TextField()),
                ('fecha_solicitud', models.DateField()),
                ('plazo_dias', models.FloatField()),
                ('id_orden_trabajo', models.CharField(max_length=100)),
                ('total_homologado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'En Proceso'), (3, 'Terminado'), (4, 'Cancelado')], default=1)),
                ('comentario', models.TextField(blank=True)),
                ('id_estatus_pte', models.ForeignKey(limit_choices_to={'nivel_afectacion': 1}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.estatus')),
                ('id_responsable_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.responsableproyecto')),
                ('id_tipo', models.ForeignKey(limit_choices_to={'nivel_afectacion': 1}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.tipo')),
            ],
            options={
                'db_table': 'pte_header',
            },
        ),
        migrations.CreateModel(
            name='PTEDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('estatus_paso', models.ForeignKey(limit_choices_to={'nivel_afectacion': 4}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.estatus')),
                ('id_paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.paso')),
                ('id_pte_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operaciones.pteheader')),
            ],
            options={
                'db_table': 'pte_detalle',
                'ordering': ['id_paso__orden'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_partida', models.CharField(max_length=100)),
                ('descripcion_concepto', models.TextField()),
                ('anexo', models.CharField(blank=True, max_length=100)),
                ('precio_unitario_mn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_unitario_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estatus', models.BooleanField(default=True)),
                ('comentario', models.TextField(blank=True)),
                ('id_sitio', models.ForeignKey(limit_choices_to={'nivel_afectacion': 1}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.sitio')),
                ('id_tipo_partida', models.ForeignKey(limit_choices_to={'nivel_afectacion': 3}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.tipo')),
                ('id_unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.unidadmedida')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_produccion', models.DateField()),
                ('volumen_produccion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volumen_actual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('importe_mn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('importe_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comentario', models.TextField(blank=True)),
                ('id_estatus_cobro', models.ForeignKey(limit_choices_to={'nivel_afectacion': 3}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.estatus')),
                ('id_ote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.ote')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.producto')),
                ('id_tipo_produccion', models.ForeignKey(limit_choices_to={'tipo': 4}, on_delete=django.db.models.deletion.CASCADE, related_name='producciones_tipo', to='operaciones.tipo')),
            ],
            options={
                'db_table': 'produccion',
            },
        ),
        migrations.AddField(
            model_name='ote',
            name='id_pte_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.pteheader'),
        ),
        migrations.AddField(
            model_name='ote',
            name='id_responsable_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.responsableproyecto'),
        ),
        migrations.AddField(
            model_name='ote',
            name='id_tipo',
            field=models.ForeignKey(limit_choices_to={'nivel_afectacion': 2}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.tipo'),
        ),
        migrations.CreateModel(
            name='EstimacionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_estimacion', models.DateField()),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('total_volumen_producido', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_volumen_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_importe_mn', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_importe_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('comentario', models.TextField(blank=True)),
                ('id_estatus_cobro', models.ForeignKey(limit_choices_to={'nivel_afectacion': 3}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.estatus')),
                ('id_ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.ote')),
            ],
            options={
                'db_table': 'estimacion_header',
            },
        ),
        migrations.CreateModel(
            name='EstimacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen_ajustado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volumen_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('comentario_ajuste', models.TextField(blank=True)),
                ('id_estatus_cobro', models.ForeignKey(limit_choices_to={'nivel_afectacion': 3}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.estatus')),
                ('id_estimacion_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operaciones.estimacionheader')),
                ('id_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.produccion')),
            ],
            options={
                'db_table': 'estimacion_detalle',
            },
        ),
    ]
