# Generated by Django 4.2.7 on 2025-10-04 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ptedetalle',
            options={'ordering': ['id_paso']},
        ),
    ]
