# Generated by Django 4.2.7 on 2025-10-07 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaProyectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_partida', models.CharField(max_length=100, verbose_name='ID Partida')),
                ('volumen_proyectado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Volumen Proyectado')),
                ('fecha_desde', models.DateField(verbose_name='Fecha Inicio Proyección')),
                ('fecha_hasta', models.DateField(verbose_name='Fecha Fin Proyección')),
                ('id_ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_proyectadas', to='operaciones.ote')),
            ],
            options={
                'verbose_name': 'Partida Proyectada',
                'verbose_name_plural': 'Partidas Proyectadas',
                'db_table': 'partida_proyectada',
                'unique_together': {('id_ot', 'id_partida', 'fecha_desde')},
            },
        ),
    ]
