# Generated by Django 4.2.7 on 2025-10-08 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_partidaproyectada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ote',
            old_name='id_estatus_ote',
            new_name='id_estatus_ot',
        ),
        migrations.RenameField(
            model_name='ote',
            old_name='oficio_ote',
            new_name='oficio_ot',
        ),
        migrations.RenameField(
            model_name='produccion',
            old_name='id_ote',
            new_name='id_ot',
        ),
    ]
