# Generated by Django 4.2.7 on 2025-10-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_alter_ptedetalle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso',
            name='importancia',
            field=models.FloatField(default=0),
        ),
    ]
