# Generated by Django 4.2.7 on 2025-10-08 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_rename_id_estatus_ote_ote_id_estatus_ot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimaciondetalle',
            old_name='volumen_ajustado',
            new_name='volumen_actual',
        ),
    ]
