# Generated by Django 4.2.7 on 2025-10-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_paso_importancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptedetalle',
            name='total_homologado',
        ),
        migrations.AddField(
            model_name='pteheader',
            name='total_homologado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
