# Generated by Django 4.2.7 on 2025-10-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_rename_volumen_ajustado_estimaciondetalle_volumen_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='clave',
            field=models.CharField(default='M', max_length=10),
            preserve_default=False,
        ),
    ]
