# Generated by Django 4.2.7 on 2025-10-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_unidadmedida_clave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='estatus',
            new_name='activo',
        ),
        migrations.AlterField(
            model_name='paso',
            name='orden',
            field=models.FloatField(default=0),
        ),
    ]
