# Generated by Django 4.2.7 on 2025-10-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_rename_estatus_producto_activo_alter_paso_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pteheader',
            name='id_estatus_pte',
        ),
    ]
