# Generated by Django 4.2.7 on 2025-10-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_remove_pteheader_id_estatus_pte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pteheader',
            name='oficio_pte',
            field=models.CharField(max_length=100),
        ),
    ]
