# Generated by Django 4.2.7 on 2025-10-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_alter_pteheader_oficio_pte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatus',
            name='nivel_afectacion',
            field=models.IntegerField(choices=[('1', 'PTE'), ('2', 'OT'), ('3', 'COBRO'), ('4', 'PASOS PTE')], default=0),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='nivel_afectacion',
            field=models.IntegerField(choices=[('1', 'PARTIDA'), ('2', 'TRABAJO')], default=0),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nivel_afectacion',
            field=models.IntegerField(choices=[('1', 'PTE'), ('2', 'OT'), ('3', 'PARTIDA'), ('4', 'PRODUCCION')], default=0),
        ),
    ]
