# Generated by Django 4.2.7 on 2025-10-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_alter_estatus_nivel_afectacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidaproyectada',
            name='volumen_real',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15, verbose_name='Volumen Real'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partidaproyectada',
            name='volumen_proyectado',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Volumen Proyectado'),
        ),
    ]
