# Generated by Django 4.2.7 on 2025-10-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_partidaproyectada_volumen_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ote',
            name='num_reprogramacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ote',
            name='ot_principal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
