# Generated by Django 4.2.7 on 2025-10-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_ote_num_reprogramacion_ote_ot_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso',
            name='orden',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
