# Generated by Django 4.2.7 on 2025-10-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_alter_paso_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso',
            name='orden',
            field=models.FloatField(default=0),
        ),
    ]
