# Generated by Django 4.2.7 on 2025-10-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0013_alter_paso_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso',
            name='tipo',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
