# Generated by Django 4.2.7 on 2025-10-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0014_paso_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso',
            name='orden',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
