# Generated by Django 4.2.7 on 2025-10-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0015_alter_paso_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptedetalle',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ptedetalle',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
