# Generated by Django 4.2.7 on 2025-10-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0016_ptedetalle_fecha_inicio_ptedetalle_fecha_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='pteheader',
            name='prioridad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
