# Generated by Django 4.2.7 on 2025-10-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0017_pteheader_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pteheader',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pteheader',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True),
        ),
    ]
