# Generated by Django 4.2.7 on 2025-10-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0018_pteheader_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarcacion',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estatus',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paso',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsableproyecto',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
