# Generated by Django 4.2.7 on 2025-10-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0019_alter_embarcacion_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='anexo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
