# Generated by Django 4.2.7 on 2025-11-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0020_alter_producto_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pteheader',
            name='id_orden_trabajo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
