# Generated by Django 4.2.7 on 2025-11-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0021_alter_pteheader_id_orden_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pteheader',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
