# Generated by Django 4.2.7 on 2025-11-04 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0022_alter_pteheader_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pteheader',
            name='id_responsable_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.responsableproyecto'),
        ),
    ]
