# Generated by Django 4.2.7 on 2025-11-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0023_alter_pteheader_id_responsable_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('evento', models.TextField(blank=True, null=True)),
                ('campo', models.TextField(blank=True, null=True)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_actual', models.TextField(blank=True, null=True)),
                ('afectacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('tabla_log', models.IntegerField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registro_actividad',
            },
        ),
    ]
