# Generated by Django 4.2.7 on 2025-11-10 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operaciones', '0025_alter_registroactividad_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividad',
            name='usuario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
