# Generated by Django 4.2.7 on 2025-11-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0026_alter_registroactividad_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptedetalle',
            name='archivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
