# Generated by Django 4.2.7 on 2025-11-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0027_ptedetalle_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ote',
            name='fecha_inicio_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ote',
            name='fecha_termino_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ote',
            name='fecha_inicio_programada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ote',
            name='fecha_termino_programada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
