# Generated by Django 4.2.7 on 2025-11-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0028_ote_fecha_inicio_real_ote_fecha_termino_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ote',
            name='orden_trabajo',
            field=models.CharField(max_length=100),
        ),
    ]
