# Generated by Django 4.2.7 on 2025-11-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0029_alter_ote_orden_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ote',
            name='monto_mxn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ote',
            name='monto_usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
