# Generated by Django 4.2.7 on 2025-11-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0030_ote_monto_mxn_ote_monto_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ote',
            old_name='fecha_inicio_programada',
            new_name='fecha_inicio_programado',
        ),
        migrations.RenameField(
            model_name='ote',
            old_name='fecha_termino_programada',
            new_name='fecha_termino_programado',
        ),
    ]
