# Generated by Django 4.2.7 on 2025-11-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0031_rename_fecha_inicio_programada_ote_fecha_inicio_programado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ote',
            name='monto_mxn',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ote',
            name='monto_usd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
