# Generated by Django 4.2.7 on 2025-11-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0032_alter_ote_monto_mxn_alter_ote_monto_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ote',
            name='monto_mxn',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='ote',
            name='monto_usd',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=15, null=True),
        ),
    ]
