# Generated by Django 4.2.7 on 2025-11-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0034_alter_ote_monto_mxn_alter_ote_monto_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='ote',
            name='id_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
