# Generated by Django 4.2.7 on 2025-11-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0035_ote_id_frente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ote',
            name='id_intercom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ote',
            name='id_patio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ote',
            name='id_plataforma',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
