# Generated by Django 4.2.7 on 2025-11-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0036_ote_id_intercom_ote_id_patio_ote_id_plataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarcacion',
            name='id_sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.sitio'),
        ),
    ]
