# Generated by Django 4.2.7 on 2025-11-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0037_embarcacion_id_sitio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('nivel_afectacion', models.IntegerField(choices=[('1', 'PARTIDA'), ('2', 'TRABAJO')], default=0)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'frente',
            },
        ),
        migrations.RemoveField(
            model_name='ote',
            name='id_embarcacion',
        ),
        migrations.RemoveField(
            model_name='sitio',
            name='nivel_afectacion',
        ),
        migrations.AddField(
            model_name='ote',
            name='id_sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.sitio'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Embarcacion',
        ),
        migrations.AddField(
            model_name='sitio',
            name='id_frente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.frente'),
        ),
    ]
