# Generated by Django 4.2.7 on 2025-11-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0038_frente_remove_ote_id_embarcacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ote',
            name='id_sitio',
        ),
        migrations.AddField(
            model_name='ote',
            name='id_embarcacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frente',
            name='nivel_afectacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
