# Generated by Django 4.2.7 on 2025-11-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0039_remove_ote_id_sitio_ote_id_embarcacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ote',
            name='plazo_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
