# Generated by Django 4.2.7 on 2025-11-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0040_ote_plazo_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasoOt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('orden', models.CharField(blank=True, max_length=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('importancia', models.FloatField(blank=True, default=0, null=True)),
                ('tipo', models.IntegerField(blank=True, default=1, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paso_ot',
                'ordering': ['orden'],
            },
        ),
    ]
