# Generated by Django 4.2.7 on 2025-11-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0041_pasoot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('archivo', models.TextField(blank=True, null=True)),
                ('estatus_paso', models.ForeignKey(limit_choices_to={'nivel_afectacion': 4}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.estatus')),
                ('id_ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operaciones.ote')),
                ('id_paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.pasoot')),
            ],
            options={
                'db_table': 'ot_detalle',
                'ordering': ['id_paso__id'],
            },
        ),
    ]
