# Generated by Django 4.2.7 on 2025-11-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0042_otdetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otdetalle',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
