# Generated by Django 4.2.7 on 2025-11-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0043_alter_otdetalle_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptedetalle',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
