# Generated by Django 4.2.7 on 2025-11-27 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0045_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pteheader',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.cliente'),
        ),
    ]
