# Generated by Django 4.2.7 on 2025-11-27 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0046_pteheader_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso',
            name='id_tipo_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.tipo'),
        ),
    ]
