# Generated by Django 4.2.7 on 2025-11-28 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0047_paso_id_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ote',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.cliente'),
        ),
    ]
