# Generated by Django 4.2.7 on 2025-12-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0048_ote_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasoot',
            name='id_tipo_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.tipo'),
        ),
    ]
