# Generated by Django 4.2.7 on 2025-12-01 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0049_pasoot_id_tipo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasoot',
            name='id_tipo_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_cliente', to='operaciones.tipo'),
        ),
        migrations.AlterField(
            model_name='pasoot',
            name='tipo',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_ot', to='operaciones.tipo'),
        ),
    ]
