# Generated by Django 4.2.7 on 2025-12-15 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0050_alter_pasoot_id_tipo_cliente_alter_pasoot_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ote',
            name='id_frente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.frente'),
        ),
        migrations.CreateModel(
            name='ReporteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(help_text='Mes numérico (1-12)')),
                ('anio', models.IntegerField(help_text='Año (Ej. 2025)')),
                ('archivo', models.URLField(blank=True, null=True, verbose_name='Link Evidencia (Drive)')),
                ('estatus_cierre', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('FIRMADO', 'Firmado')], default='ABIERTO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_mensuales', to='operaciones.ote')),
            ],
            options={
                'verbose_name': 'Reporte Mensual',
                'verbose_name_plural': 'Reportes Mensuales',
                'db_table': 'reporte_mensual_header',
                'unique_together': {('id_ot', 'mes', 'anio')},
            },
        ),
        migrations.AddField(
            model_name='produccion',
            name='id_reporte_mensual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='operaciones.reportemensual'),
        ),
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estatus', models.CharField(choices=[('OK', 'Completo (OK)'), ('FFP', 'Falta Firma PEP (FFP)'), ('FFC', 'Falta Firma CIA (FFC)'), ('S', 'Suspendida (S)'), ('BAJA', 'Baja por Equipo/Personal'), ('NA', 'No Aplica / Inactivo'), ('ELABORADO', 'Elaborado (Pendiente Firma)')], default='ELABORADO', max_length=20)),
                ('comentario', models.CharField(blank=True, help_text='Observación breve del día', max_length=255, null=True)),
                ('bloqueado', models.BooleanField(default=False)),
                ('id_reporte_mensual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dias_estatus', to='operaciones.reportemensual')),
            ],
            options={
                'db_table': 'reporte_diario_estatus',
                'indexes': [models.Index(fields=['fecha'], name='reporte_dia_fecha_631bd9_idx')],
                'unique_together': {('id_reporte_mensual', 'fecha')},
            },
        ),
    ]
