# Generated by Django 4.2.7 on 2025-12-15 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0051_alter_ote_id_frente_reportemensual_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportediario',
            new_name='reporte_dia_fecha_b0fd1e_idx',
            old_name='reporte_dia_fecha_631bd9_idx',
        ),
        migrations.AlterModelTable(
            name='reportediario',
            table='reporte_diario_detalle',
        ),
    ]
