# Generated by Django 4.2.7 on 2025-12-16 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0052_rename_reporte_dia_fecha_631bd9_idx_reporte_dia_fecha_b0fd1e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='id_ot',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='reportediario',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='reportemensual',
            name='estatus_cierre',
        ),
        migrations.AddField(
            model_name='produccion',
            name='es_excedente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produccion',
            name='tipo_tiempo',
            field=models.CharField(blank=True, choices=[('TE', 'Tiempo Efectivo'), ('CMA', 'Costo Mínimo/Muerto')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='id_estatus',
            field=models.ForeignKey(default=1, limit_choices_to={'nivel_afectacion': 6}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.estatus', verbose_name='Estatus Operativo'),
        ),
        migrations.AddField(
            model_name='reportemensual',
            name='id_estatus',
            field=models.ForeignKey(default=1, limit_choices_to={'nivel_afectacion': 5}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.estatus', verbose_name='Estatus Cierre'),
        ),
        migrations.CreateModel(
            name='RegistroGPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Evidencia Fotográfica')),
                ('nota_bloqueo', models.TextField(blank=True, verbose_name='Alerta por Excedente/No Considerado')),
                ('id_estatus', models.ForeignKey(limit_choices_to={'nivel_afectacion': 6}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.estatus', verbose_name='Estatus GPU')),
                ('id_estimacion_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.estimaciondetalle')),
                ('id_produccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpu', to='operaciones.produccion')),
            ],
            options={
                'db_table': 'registro_generadores_pu',
            },
        ),
        migrations.CreateModel(
            name='PartidaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen_autorizado', models.DecimalField(decimal_places=4, max_digits=15)),
                ('id_ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto_partidas', to='operaciones.ote')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operaciones.producto')),
            ],
            options={
                'db_table': 'partida_anexo_ot',
                'unique_together': {('id_ot', 'id_producto')},
            },
        ),
        migrations.AddField(
            model_name='produccion',
            name='id_partida_anexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion', to='operaciones.partidaanexo'),
        ),
    ]
