# Generated by Django 4.2.7 on 2025-12-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0053_remove_produccion_id_ot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ote',
            name='monto_mxn',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='ote',
            name='monto_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
    ]
