# Generated by Django 4.2.7 on 2026-01-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0054_alter_ote_monto_mxn_alter_ote_monto_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ote',
            name='id_pte_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.pteheader'),
        ),
    ]
