# Generated by Django 4.2.7 on 2026-01-03 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import operaciones.models.ote_models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operaciones', '0055_alter_ote_id_pte_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_excel', models.FileField(upload_to=operaciones.models.ote_models.generar_ruta_anexo)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('es_activo', models.BooleanField(default=True)),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones_anexo', to='operaciones.ote')),
                ('usuario_carga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartidaAnexoImportada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_partida', models.CharField(max_length=10)),
                ('descripcion_concepto', models.TextField()),
                ('volumen_proyectado', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_unitario_mn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_unitario_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('orden_fila', models.IntegerField()),
                ('importacion_anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='operaciones.importacionanexo')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.unidadmedida')),
            ],
        ),
    ]
