# Generated by Django 4.2.7 on 2026-01-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0056_importacionanexo_partidaanexoimportada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importacionanexo',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='partidaanexoimportada',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='importacionanexo',
            table='importacion_anexo',
        ),
        migrations.AlterModelTable(
            name='partidaanexoimportada',
            table='partida_anexo_importada',
        ),
    ]
