# Generated by Django 4.2.7 on 2026-01-08 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0057_alter_importacionanexo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_frente',
            field=models.ForeignKey(blank=True, limit_choices_to={'nivel_afectacion': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.frente'),
        ),
    ]
