# Generated by Django 4.2.7 on 2026-01-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0058_producto_id_frente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_sitio',
        ),
    ]
