# Generated by Django 4.2.7 on 2026-01-10 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0059_remove_producto_id_sitio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_frente',
        ),
        migrations.AddField(
            model_name='producto',
            name='id_sitio',
            field=models.ForeignKey(blank=True, limit_choices_to={'nivel_afectacion': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.sitio'),
        ),
    ]
