# Generated by Django 4.2.7 on 2026-01-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0060_remove_producto_id_frente_producto_id_sitio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion_concepto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario_mn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
