# Generated by Django 4.2.7 on 2026-01-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0061_alter_producto_descripcion_concepto_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produccion',
            unique_together={('id_partida_anexo', 'fecha_produccion')},
        ),
        migrations.AddIndex(
            model_name='produccion',
            index=models.Index(fields=['fecha_produccion'], name='produccion_fecha_p_da774f_idx'),
        ),
        migrations.AddIndex(
            model_name='produccion',
            index=models.Index(fields=['id_partida_anexo'], name='produccion_id_part_fc4373_idx'),
        ),
    ]
