# Generated by Django 4.2.7 on 2026-01-13 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0062_alter_produccion_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='id_tipo_produccion',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='importe_mn',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='importe_usd',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='volumen_actual',
        ),
        migrations.AlterField(
            model_name='produccion',
            name='id_partida_anexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_produccion', to='operaciones.partidaanexoimportada'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='tipo_tiempo',
            field=models.CharField(blank=True, choices=[('TE', 'Tiempo Efectivo'), ('CMA', 'Costo Mínimo Aplicado')], max_length=3, null=True),
        ),
    ]
