# Generated by Django 4.2.7 on 2026-01-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0063_remove_produccion_id_tipo_produccion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produccion',
            unique_together={('id_partida_anexo', 'fecha_produccion', 'tipo_tiempo')},
        ),
        migrations.AddIndex(
            model_name='produccion',
            index=models.Index(fields=['tipo_tiempo'], name='produccion_tipo_ti_7fcb61_idx'),
        ),
    ]
