# Generated by Django 4.2.7 on 2026-01-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0064_alter_produccion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidaanexoimportada',
            name='precio_unitario_mn',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='partidaanexoimportada',
            name='precio_unitario_usd',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='partidaanexoimportada',
            name='volumen_proyectado',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='volumen_produccion',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
