# Generated by Django 4.2.7 on 2026-01-13 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0065_alter_partidaanexoimportada_precio_unitario_mn_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartidaAnexo',
        ),
    ]
