# Generated by Django 4.2.7 on 2026-01-22 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0066_delete_partidaanexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Anexo C', max_length=100)),
                ('tipo', models.CharField(choices=[('TECNICO', 'Anexo Técnico (Especificaciones)'), ('FINANCIERO', 'Anexo C (Lista de Precios)'), ('LEGAL', 'Legal/Administrativo')], default='FINANCIERO', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='contratos/anexos_maestros/')),
                ('monto_mn', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('monto_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'contrato_anexo_maestro',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría Técnica',
                'db_table': 'cat_categoria',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='operaciones.categoria')),
            ],
            options={
                'db_table': 'cat_subcategoria',
                'unique_together': {('categoria', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='SubAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_anexo', models.CharField(help_text='Ej. C-2, C-2-CR, Anexo B1', max_length=50)),
                ('descripcion', models.TextField(help_text='Ej. Suministro y prefabricación de estructuras...')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('precio_unitario_mn', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('precio_unitario_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('importe_mn', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('importe_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('activo', models.BooleanField(default=True)),
                ('anexo_maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_anexos', to='operaciones.anexocontrato')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.unidadmedida')),
            ],
            options={
                'db_table': 'contrato_sub_anexo',
                'ordering': ['clave_anexo'],
                'unique_together': {('anexo_maestro', 'clave_anexo')},
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='No. Contrato')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('monto_mn', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('monto_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operaciones.cliente')),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='operaciones.subcategoria')),
            ],
            options={
                'db_table': 'cat_clasificacion',
                'unique_together': {('subcategoria', 'clave')},
            },
        ),
        migrations.AddField(
            model_name='anexocontrato',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_maestros', to='operaciones.contrato'),
        ),
        migrations.CreateModel(
            name='ConceptoMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida_ordinaria', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_interno', models.CharField(blank=True, help_text='Código interno', max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('precio_unitario_mn', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('precio_unitario_usd', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('partida_extraordinaria', models.CharField(blank=True, max_length=50, null=True)),
                ('pte_creacion', models.CharField(blank=True, help_text='PTE de origen', max_length=100, null=True)),
                ('ot_creacion', models.CharField(blank=True, help_text='OT de origen', max_length=100, null=True)),
                ('fecha_autorizacion', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=20, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.categoria')),
                ('clasificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.clasificacion')),
                ('id_tipo_partida', models.ForeignKey(limit_choices_to={'nivel_afectacion': 3}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.tipo')),
                ('sub_anexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='operaciones.subanexo')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.subcategoria')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operaciones.unidadmedida')),
            ],
            options={
                'db_table': 'contrato_concepto_maestro',
                'indexes': [models.Index(fields=['partida_ordinaria'], name='contrato_co_partida_ccd493_idx'), models.Index(fields=['sub_anexo'], name='contrato_co_sub_ane_8cc1b3_idx')],
                'unique_together': {('sub_anexo', 'partida_ordinaria')},
            },
        ),
    ]
