# Generated by Django 4.2.7 on 2026-01-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0067_anexocontrato_categoria_subcategoria_subanexo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anexocontrato',
            old_name='nombre',
            new_name='descripcion',
        ),
    ]
