# Generated by Django 4.2.7 on 2026-01-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0068_rename_nombre_anexocontrato_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexocontrato',
            name='clave',
            field=models.CharField(default='Anexo c', max_length=100),
            preserve_default=False,
        ),
    ]
