# Generated by Django 4.2.7 on 2026-01-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0069_anexocontrato_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexocontrato',
            name='clave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anexocontrato',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
