# Generated by Django 4.2.7 on 2026-01-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0071_alter_conceptomaestro_precio_unitario_mn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptomaestro',
            name='precio_unitario_mn',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='conceptomaestro',
            name='precio_unitario_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
    ]
