# Generated by Django 4.2.7 on 2026-01-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0073_alter_categoria_clave_alter_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
