# Generated by Django 4.2.7 on 2026-01-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0074_alter_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptomaestro',
            name='categoria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conceptomaestro',
            name='clasificacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conceptomaestro',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conceptomaestro',
            name='ot_creacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conceptomaestro',
            name='pte_creacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conceptomaestro',
            name='subcategoria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subanexo',
            name='clave_anexo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subanexo',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
