# Generated by Django 4.2.7 on 2026-01-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0075_alter_conceptomaestro_categoria_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conceptomaestro',
            unique_together=set(),
        ),
    ]
