# Generated by Django 4.2.7 on 2026-01-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0076_alter_conceptomaestro_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidaanexoimportada',
            name='anexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
