# Generated by Django 4.2.7 on 2026-01-30 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0077_partidaanexoimportada_anexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partidaproyectada',
            options={'verbose_name': 'Programación Diaria', 'verbose_name_plural': 'Programaciones Diarias'},
        ),
        migrations.AlterUniqueTogether(
            name='partidaproyectada',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='partidaproyectada',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partidaproyectada',
            name='partida_anexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programacion_diaria', to='operaciones.partidaanexoimportada'),
        ),
        migrations.AddField(
            model_name='partidaproyectada',
            name='volumen_programado',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='partidaproyectada',
            unique_together={('partida_anexo', 'fecha')},
        ),
        migrations.AlterModelTable(
            name='partidaproyectada',
            table=None,
        ),
        migrations.RemoveField(
            model_name='partidaproyectada',
            name='fecha_desde',
        ),
        migrations.RemoveField(
            model_name='partidaproyectada',
            name='fecha_hasta',
        ),
        migrations.RemoveField(
            model_name='partidaproyectada',
            name='id_ot',
        ),
        migrations.RemoveField(
            model_name='partidaproyectada',
            name='id_partida',
        ),
        migrations.RemoveField(
            model_name='partidaproyectada',
            name='volumen_proyectado',
        ),
        migrations.RemoveField(
            model_name='partidaproyectada',
            name='volumen_real',
        ),
    ]
