# Generated by Django 4.2.7 on 2026-01-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0078_alter_partidaproyectada_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidaproyectada',
            name='ot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.ote'),
        ),
    ]
