# Generated by Django 4.2.7 on 2026-01-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0079_partidaproyectada_ot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partidaproyectada',
            unique_together=set(),
        ),
    ]
