# Generated by Django 4.2.7 on 2026-01-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0080_alter_partidaproyectada_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partidaproyectada',
            options={'verbose_name': 'Partida Proyectada', 'verbose_name_plural': 'Partidas Proyectadas'},
        ),
        migrations.AlterModelTable(
            name='partidaproyectada',
            table='partida_proyectada',
        ),
    ]
