# Generated by Django 4.2.7 on 2026-02-06 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0081_alter_partidaproyectada_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superintendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('sitio_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.sitio')),
            ],
            options={
                'db_table': 'superintendente',
            },
        ),
        migrations.CreateModel(
            name='CicloGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_super_a', models.DateField(help_text='Fecha en que inició guardia el Super A')),
                ('sitio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operaciones.sitio')),
                ('super_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_a', to='operaciones.superintendente')),
                ('super_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_b', to='operaciones.superintendente')),
            ],
            options={
                'db_table': 'guardias',
            },
        ),
    ]
