# Generated by Django 4.2.7 on 2026-02-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0082_superintendente_cicloguardia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ote',
            name='fecha_fin_patio',
            field=models.DateField(blank=True, null=True, verbose_name='Fin Fase Patio'),
        ),
        migrations.AddField(
            model_name='ote',
            name='fecha_inicio_patio',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio Fase Patio'),
        ),
        migrations.AddField(
            model_name='ote',
            name='requiere_patio',
            field=models.BooleanField(default=False, verbose_name='Requiere Fase en Patio'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='id_sitio_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.sitio'),
        ),
    ]
