# Generated by Django 4.2.7 on 2026-02-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0083_ote_fecha_fin_patio_ote_fecha_inicio_patio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produccion',
            unique_together={('id_partida_anexo', 'fecha_produccion', 'tipo_tiempo', 'id_sitio_produccion')},
        ),
    ]
