# Generated by Django 4.2.7 on 2026-02-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0084_alter_produccion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportediario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='id_sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.sitio'),
        ),
        migrations.AlterUniqueTogether(
            name='reportediario',
            unique_together={('id_reporte_mensual', 'fecha', 'id_sitio')},
        ),
    ]
