# Generated by Django 4.2.7 on 2026-02-13 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0085_alter_reportediario_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_version', models.CharField(max_length=150)),
                ('archivo_mpp', models.FileField(upload_to='cronogramas/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('es_vigente', models.BooleanField(default=True)),
                ('fecha_inicio_proyecto', models.DateField(blank=True, null=True)),
                ('fecha_fin_proyecto', models.DateField(blank=True, null=True)),
                ('id_ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='operaciones.ote')),
            ],
            options={
                'db_table': 'importacion_cronograma',
            },
        ),
        migrations.AddField(
            model_name='registrogpu',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registrogpu',
            name='nota_bloqueo',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.CreateModel(
            name='TareaCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_project', models.IntegerField()),
                ('id_project', models.IntegerField()),
                ('wbs', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=500)),
                ('nivel_esquema', models.IntegerField(default=0)),
                ('es_resumen', models.BooleanField(default=False)),
                ('padre_uid', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('duracion_dias', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentaje_mpp', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='operaciones.cronogramaversion')),
            ],
            options={
                'db_table': 'importacion_cronograma_tarea',
            },
        ),
        migrations.CreateModel(
            name='AvanceCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_real', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_cliente', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comentario', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avance', to='operaciones.tareacronograma')),
            ],
            options={
                'db_table': 'importacion_cronograma_avance',
            },
        ),
        migrations.AddIndex(
            model_name='tareacronograma',
            index=models.Index(fields=['version', 'uid_project'], name='importacion_version_7a8132_idx'),
        ),
    ]
