# Generated by Django 4.2.7 on 2026-02-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0086_cronogramaversion_registrogpu_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrogpu',
            name='nota_bloqueo',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
