# Generated by Django 4.2.7 on 2026-02-19 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0087_alter_registrogpu_nota_bloqueo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareacronograma',
            name='porcentaje_completado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tareacronograma',
            name='recursos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DependenciaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea_predecesora_uid', models.IntegerField()),
                ('tarea_sucesora_uid', models.IntegerField()),
                ('tipo', models.CharField(choices=[('FS', 'Fin a Inicio'), ('SS', 'Inicio a Inicio'), ('FF', 'Fin a Fin'), ('SF', 'Inicio a Fin')], default='FS', max_length=2)),
                ('lag_dias', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='operaciones.cronogramaversion')),
            ],
            options={
                'db_table': 'importacion_cronograma_dependencia',
            },
        ),
    ]
