# Generated by Django 4.2.7 on 2026-02-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0088_tareacronograma_porcentaje_completado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronogramaversion',
            old_name='es_vigente',
            new_name='es_activo',
        ),
    ]
