# Generated by Django 4.2.7 on 2026-02-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0089_rename_es_vigente_cronogramaversion_es_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronogramaversion',
            name='archivo_mpp',
            field=models.FileField(upload_to='operaciones/mpps/'),
        ),
    ]
