# Generated by Django 4.2.7 on 2026-02-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0090_alter_cronogramaversion_archivo_mpp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pteheader',
            options={'permissions': [('view_centro_consulta', 'Puede visualizar el centro de consulta')]},
        ),
    ]
