# Generated by Django 4.2.7 on 2026-03-09 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operaciones', '0091_alter_pteheader_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDiarioEmbarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Pre-Cierre', 'Pre-Cierre'), ('Cerrado', 'Cerrado')], default='Borrador', max_length=20)),
                ('sin_arribos', models.BooleanField(default=False)),
                ('archivo_pdf_url', models.URLField(blank=True, null=True)),
                ('comentarios_generales', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.sitio')),
                ('representante', models.ForeignKey(help_text='Usuario que elabora/firma el reporte', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Diario de Embarcación',
                'verbose_name_plural': 'Reportes Diarios de Embarcaciones',
                'db_table': 'reporte_diario_embarcacion',
                'unique_together': {('embarcacion', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='InventarioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recurso', models.CharField(choices=[('DIESEL', 'Diésel'), ('AGUA', 'Agua Dulce')], max_length=50)),
                ('existencia_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('suministro', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consumo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='operaciones.reportediarioembarcacion')),
            ],
            options={
                'verbose_name': 'Inventario Diario',
                'verbose_name_plural': 'Inventarios Diarios',
                'db_table': 'inventario_diario',
            },
        ),
        migrations.CreateModel(
            name='BitacoraTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('actividad', models.CharField(max_length=255)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos', to='operaciones.reportediarioembarcacion')),
            ],
            options={
                'verbose_name': 'Bitácora de Tiempo',
                'verbose_name_plural': 'Bitácoras de Tiempo',
                'db_table': 'bitacora_tiempo',
            },
        ),
    ]
