# Generated by Django 4.2.7 on 2026-03-11 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0092_reportediarioembarcacion_inventariodiario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariodiario',
            name='reporte',
        ),
        migrations.AlterUniqueTogether(
            name='reportediarioembarcacion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reportediarioembarcacion',
            name='embarcacion',
        ),
        migrations.RemoveField(
            model_name='reportediarioembarcacion',
            name='representante',
        ),
        migrations.DeleteModel(
            name='BitacoraTiempo',
        ),
        migrations.DeleteModel(
            name='InventarioDiario',
        ),
        migrations.DeleteModel(
            name='ReporteDiarioEmbarcacion',
        ),
    ]
